CREATE DATABASE SQL_HOSPITAL;

USE SQL_HOSPITAL;

CREATE TABLE PATIENTS(
DATE VARCHAR(12),
 P_ID VARCHAR(6) NOT NULL,
 P_NAME VARCHAR(10),
 AGE INT,
 WEIGHT INT,
 GENDER VARCHAR(10),
 LOCATION VARCHAR(10),
 PH_NO INT,
 DISEASE VARCHAR(10),
 DOC_N VARCHAR(10),
 DOC_ID INT NOT NULL) 


INSERT INTO 
PATIENTS(DATE,P_ID,P_NAME,AGE,WEIGHT,GENDER,LOCATION,PH_NO,DISEASE,DOC_N,D
OC_ID)
VALUES("15-06-2019", "AP2021", "Sarath", "67", "76", "Male", "Chennai", "5462829", 
"Cardiac", "Mohan", "21"),
("13-02-2019", "AP2022", "John", "62", "80", "Male", "Banglore", "1234731", "Cancer", 
"Suraj", "22"),
("08-01-2018", "AP2023", "Henry", "43", "65", "Male", "Kerala", "9028320", "Liver", 
"Mehta", "23"),
("04-02-2020", "AP2024", "Carl", "56", "72", "Female", "Mumbai", "9293829", "Asthma", 
"Karthik", "24"),
("15-09-2017", "AP2025", "Shikar", "55", "71", "Male", "Delhi", "7821281", "Cardiac", 
"Mohan", "21"),
("22-07-2018", "AP2026", "Piysuh", "47", "59", "Male", "Haryana", "8912819", "Cancer", 
"Suraj", "22"),
("25-03-2017", "AP2027", "Stephen", "69", "55", "Male", "Gujarat", "8888211", "Liver", 
"Mehta", "23"),
("22-04-2019", "AP2028", "Aaron", "75", "53", "Male", "Banglore", "9012192", "Asthma", 
"Karthik", "24");


SELECT * FROM PATIENTS;


SELECT COUNT(P_ID) FROM PATIENTS;


SELECT P_ID, P_NAME, GENDER, DISEASE
FROM PATIENTS
ORDER BY AGE DESC
LIMIT 1;


SELECT P_ID,P_NAME,CURRENT_DATE() FROM PATIENTS;


SELECT 
(SELECT UPPER(P_NAME) FROM patients WHERE STR_TO_DATE(date, '%d-%m-%Y') = ( 
SELECT Min(STR_TO_DATE(date, '%d-%m-%Y')) FROM PATIENTS) ) AS old_PATIENT ,
 (SELECT UPPER(P_NAME) FROM patients WHERE STR_TO_DATE(date, '%d-%m-%Y') = ( 
SELECT MAX(STR_TO_DATE(date, '%d-%m-%Y')) FROM PATIENTS) ) AS 
NEW_PATIENT
FROM PATIENTS
LIMIT 1; 


SELECT P_NAME,LENGTH(P_NAME) FROM PATIENTS; 


SELECT P_NAME,MID(GENDER,1,1) FROM PATIENTS;


SELECT CONCAT(P_NAME,DOC_N) AS PERSONS FROM PATIENTS;


SELECT AGE,LOG10(AGE) AS NEW_VALUE FROM PATIENTS;


SELECT EXTRACT(YEAR FROM STR_TO_DATE(DATE, '%d-%m-%Y')) AS YEAR FROM 
PATIENTS;


SELECT IF(lower(P_NAME) = lower(DOC_N), "NULL", P_NAME) AS RESULT FROM 
PATIENTS;


SELECT IF(AGE>40 , "YES","NO") AS RESULT FROM PATIENTS;


SELECT DOC_N FROM PATIENTS
GROUP BY DOC_N
HAVING COUNT(*)>1;