CREATE DATABASE EMPLOYEE;
USE EMPLOYEE; 

SELECT EMP_ID,FIRST_NAME,LAST_NAME,GENDER,DEPT 
	FROM emp_record;

SELECT EMP_ID,FIRST_NAME,LAST_NAME,GENDER,DEPT,EMP_RATING
FROM EMP_RECORD
WHERE EMP_RATING < 2 ;

SELECT EMP_ID,FIRST_NAME,LAST_NAME,GENDER,DEPT,EMP_RATING
FROM EMP_RECORD
WHERE EMP_RATING > 4;

SELECT EMP_ID,FIRST_NAME,LAST_NAME,GENDER,DEPT,EMP_RATING
FROM EMP_RECORD
WHERE EMP_RATING BETWEEN 2 AND 4;

SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS NAME
FROM EMP_RECORD
WHERE DEPT='FINANCE';

SELECT e.EMP_ID,e.FIRST_NAME,e.LAST_NAME,COUNT(m.EMP_ID) AS REPORTERS_COUNT
FROM EMP_RECORD e 
JOIN EMP_RECORD m
ON e.EMP_ID = m.MANAGER_ID
GROUP BY e.EMP_ID,e.FIRST_NAME,e.LAST_NAME
HAVING COUNT(m.EMP_ID)>0;



SELECT * FROM EMP_RECORD
WHERE DEPT='HEALTHCARE'
UNION 
SELECT * FROM EMP_RECORD
WHERE DEPT='FINANCE';

SELECT EMP_ID,FIRST_NAME,LAST_NAME,ROLE,DEPT,
(SELECT MAX(EMP_RATING)  
FROM EMP_RECORD E2
WHERE E1.DEPT=E2.DEPT
GROUP BY DEPT
) AS MAX_EMP_RATINGS        
FROM EMP_RECORD E1
GROUP BY EMP_ID,FIRST_NAME,LAST_NAME,ROLE,DEPT;


SELECT MIN(SALARY) AS MIN_SALARY, MAX(SALARY) AS MAX_SALARY,ROLE
FROM EMP_RECORD
GROUP BY ROLE;


SELECT EMP_ID,FIRST_NAME,LAST_NAME,EXP,
RANK() OVER (ORDER BY EXP DESC) AS EXPERIENCE_RANK
FROM EMP_RECORD;


CREATE VIEW EMP_SALARY_VIEW AS 
SELECT EMP_ID,FIRST_NAME,LAST_NAME,SALARY,COUNTRY
FROM EMP_RECORD
WHERE SALARY>6000;
SELECT * FROM EMP_SALARY_VIEW;


SELECT EMP_ID,CONCAT(FIRST_NAME," ",LAST_NAME) AS NAME , EXP
FROM EMP_RECORD 
WHERE EXP > (
SELECT MAX(EXP) - 10
FROM EMP_RECORD);



DELIMITER $$
CREATE PROCEDURE EMP_DETAILS_PROC()
BEGIN
SELECT * FROM EMP_RECORD
WHERE EXP>3;
END $$
CALL EMP_DETAILS_PROC();


DROP FUNCTION IF EXISTS JOB_PROFILE_FUN;
DELIMITER &&
CREATE FUNCTION JOB_PROFILE_FUN(EXP INT)
RETURNS VARCHAR(50)
DETERMINISTIC
BEGIN
DECLARE JOB_PROFILE VARCHAR(50);
IF EXP<=2 THEN
SET JOB_PROFILE = 'JUNIOR DATA SCIENTIST';
ELSEIF EXP<=5 THEN
SET JOB_PROFILE = 'ASSOCIATE DATA SCIENTIST';
ELSEIF EXP<=10 THEN
SET JOB_PROFILE = 'SENIOR DATA SCIENTIST';   
ELSEIF EXP<=12 THEN
SET JOB_PROFILE = 'LEAD DATA SCIENTIST';  
ELSEIF EXP<=16 THEN
SET JOB_PROFILE = 'MANAGER'; 
END IF;
RETURN(JOB_PROFILE);
END &&
DELIMITER ;

SELECT EMP_ID,CONCAT(FIRST_NAME," ",LAST_NAME) AS NAME,ROLE,JOB_PROFILE_FUN(EXP) AS JOB_PROFILE_SET FROM data_science_team;


CREATE INDEX IND_FNAME ON EMP_RECORD(FIRST_NAME(50)); 
EXPLAIN SELECT * FROM EMP_RECORD
WHERE FIRST_NAME='RIC';


SELECT EMP_ID,FIRST_NAME,LAST_NAME,
(0.05*SALARY) * EMP_RATING  AS BONUS   
FROM EMP_RECORD ;


SELECT CONTINENT,COUNTRY,AVG(SALARY) AS AVERAGE_SALARY
FROM EMP_RECORD
GROUP BY CONTINENT, COUNTRY;
